export const CATEGORIES = [
  { oldPath: "/love", path: "/categories/love", name: "恋愛" },
  { oldPath: "/study", path: "/categories/study", name: "勉強" },
  { oldPath: "/life", path: "/categories/life", name: "人生相談" },
  { oldPath: "/fortune", path: "/categories/fortune", name: "占い・運勢" },
  { oldPath: "/math", path: "/categories/math", name: "数学・算数" },
  { oldPath: "/mental", path: "/categories/mental", name: "心の悩み" },
  { oldPath: "/path", path: "/categories/graduation-path", name: "進路" },
  { oldPath: "/diet", path: "/categories/diet", name: "ダイエット" },
  { oldPath: "/work", path: "/categories/work", name: "仕事" },
  { oldPath: "/tenshoku", path: "/categories/jobs", name: "転職" },
  { oldPath: "/omikuji", path: "/categories/omikuji", name: "おみくじ" },
  { oldPath: "/money", path: "/categories/money", name: "お金" },
  { oldPath: "/health", path: "/categories/health", name: "健康" },
  { oldPath: "/eikaiwa", path: "/categories/english-talk", name: "英会話" },
  { oldPath: "/kobun", path: "/categories/kobun", name: "古文" },
  { oldPath: "/shukatsu", path: "/categories/shukatsu", name: "就職" },
  { oldPath: "/sekaishi", path: "/categories/world-history", name: "世界史" },
  { oldPath: "/ikuji", path: "/categories/raising-children", name: "子育て" },
  { oldPath: "/family", path: "/categories/family", name: "家族" },
  { oldPath: "/travel", path: "/categories/travel", name: "旅行" },
  { oldPath: "/anime", path: "/categories/anime", name: "アニメ" },
  { oldPath: "/rikon", path: "/categories/divorce", name: "離婚" },
  { oldPath: "/futoukou", path: "/categories/futoko", name: "不登校" },
  { oldPath: "/souzoku", path: "/categories/sozoku", name: "相続" },
  { oldPath: "/marriage", path: "/categories/marriage", name: "結婚" },
];
